on: [push, pull_request]
name: Toot, together!
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: derickr/toot-together-action@visibility-option
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  toot:
    name: Toot
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: checkout master
        uses: actions/checkout@v2
      - name: Toot
        uses: derickr/toot-together-action@visibility-option
        with:
          visibility: "public"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # URL to the instance hosting your Mastodon account
          MASTODON_URL: https://fosstodon.org/
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
